mina-arena/mina-arena

client/src/lib/components/sandbox/play/phase-input/PhaseInput.svelte, client/src/lib/components/sandbox/play/phase-input/ShootingPhaseInput.svelte, client/src/lib/mina-arena-graphql-client/MinaArenaClient.ts, client/src/types.d.ts
We don't yet have any rendering of the shooting phase on the client, nor do we support submission of any ranged attacks.
Add template to render during shooting phase, add support for submitting ranged attacks.
A PR to `mina-arena-server` will update it to include all 3 move/shoot/melee phases, it's currently just movement phase back and forth.
Prime: @45930
=> Ability to submit shooting phase with ranged attacks

client/src/lib/components/sandbox/play/phase-input/MeleePhaseInput.svelte, client/src/lib/components/sandbox/play/phase-input/PhaseInput.svelte, client/src/lib/mina-arena-graphql-client/MinaArenaClient.ts, client/src/types.d.ts
Just like #14 but for melee phase.
Support submission of melee phase with melee attacks.
In testing this I noticed that dead pieces are still rendered on the board, and they should probably also be excluded from the list of units you can give orders to. A follow-up PR will handle that.
Also I may need to modify the max melee range constant from 5 to something a bit larger. 5 means you have to be practically right on top of them.
Prime: @45930
=> Ability to submit melee phase with melee attacks

client/src/lib/components/sandbox/play/Arena.svelte, client/src/lib/components/sandbox/play/phase-input/MeleePhaseInput.svelte, client/src/lib/components/sandbox/play/phase-input/MovementPhaseInput.svelte, client/src/lib/components/sandbox/play/phase-input/ShootingPhaseInput.svelte
We render all GamePieces regardless of whether they're living or dead. We also show all living and dead GamePieces in the list of pieces you can give orders to or target for attacks, which is wrong.
Also, if you enter the ID of an enemy piece you want to attack, and then clear out the input box, it does not currently remove the queued attack, it just modifies the queued attack to have a target piece ID of `null` which results in the phase submission being rejected.
Only render living GamePieces, and only include living GamePieces in the list of pieces you can give orders to or target. Handle clearing of target piece input box.
Prime: @45930
=> Do not render dead pieces, allow removal of queued attacks

client/src/lib/components/sandbox/play/Arena.svelte, client/src/lib/components/sandbox/play/utils.ts, client/src/types.d.ts
GamePieces are currently rendered as squares, positioned with their top-left corner on the point of the piece's coordinates. We will ultimately probably want units to be circles, likely with some image filled in such as a character portrait or a simple icon indicating which unit it is.
Draw pieces as circles centered on the point at which the piece's coordinates are.
Prime: @45930
=> Render game pieces as circles

client/src/lib/components/sandbox/play/MainGamePage.svelte, client/src/lib/mina-arena-graphql-client/queries/get-game.ts, client/src/types.d.ts
Currently if you play a game to its conclusion (all pieces dead on one side) the UI just renders the "current phase" and all its inputs and doesn't indicate the game is over, even though if you look at the API response from the server it does show that the game has status `COMPLETED`.
Add a very basic "game over" state to display when the game is done, and don't allow the user to input more orders.
Obviously this is ugly currently but it does get us to a place where you can play a game to the end and see who won!
Prime: @45930
=> Add game over state

client/src/app.css, client/src/lib/components/sandbox/play/Arena.svelte, client/src/lib/components/sandbox/play/utils.ts, client/src/types.d.ts
The game would be much more ergonomic if the user could interact via the mouse instead of entering unit orders via text inputs.
Lay some groundwork for handling mouse events. This PR allows the user to hover the mouse over a GamePiece and shows a tooltip with some details about the piece/unit. It also allows the user to click a GamePiece on the board to select it, highlighting the selected piece.
A follow-up PR will allow the user to issue move orders to selected units using the mouse.
https://github.com/trumpet-zk-ignite-1/mina-arena/assets/8811423/cd35c16c-8704-4dd1-b85e-e2a8db35809d
Prime: @45930
=> Display piece details on hover, allow selecting piece

client/.env.example, client/src/lib/components/sandbox/play/MainGamePage.svelte, client/src/lib/dice-service-client/DiceRollServiceClient.ts, client/src/lib/dice-service-client/snarky-js-smoke-test.ts, client/src/routes/enter/+page.svelte
Prime: @louiswheeleriv 
Adding a dice roll client which calls out to mina-rng.  You should be able to use this with each piece's attack phases.
The way we implemented attacks in the server, I think we actually need to get 1 roll at a time always, not a variable number or rolls based on the unit's number of attacks.  So if there are 3 attacks for a unit, we should call out 3 times to the API.  Maybe we can go into the mina-rng server and make a more effecient response of exactly what we need (an array of individually signed single-rolls, vs a signed message of 3 rolls together).
=> Implement dice roll client

client/src/app.html, client/src/lib/components/sandbox/arena/ArenaCanvasMeleePhase.svelte, client/src/lib/components/sandbox/arena/ArenaCanvasMovementPhase.svelte, client/src/lib/components/sandbox/arena/ArenaCanvasShootingPhase.svelte, client/src/lib/components/sandbox/arena/SubmitPhaseButton.svelte
Currently when you submit your phase orders, which takes about 15 seconds for the movement phase, we do not show any kind of loading state, still allowing the user to click the Submit Phase button during that time.
Add a loading state after submitting phase orders.
https://github.com/trumpet-zk-ignite-1/mina-arena/assets/8811423/01dace96-3d79-4047-8779-a797d5857637
=> Add loading state after submitting phase orders

client/src/lib/components/sandbox/arena/ArenaActionLog.svelte, client/src/lib/components/sandbox/play/Arena.svelte, client/src/lib/components/sandbox/play/MainGamePage.svelte, client/src/lib/mina-arena-graphql-client/queries/get-game-status.ts, client/src/lib/mina-arena-graphql-client/queries/get-game.ts, client/src/types.d.ts
Prime @45930 
Currently the user doesn't have a great view into what happened in the previous phase which was just resolved. Did I do damage? What even happened?
Add a simple action log on the side, somewhat like a chat box, which displays the actions which happened in the previous phase.
https://github.com/trumpet-zk-ignite-1/mina-arena/assets/8811423/a430f390-564d-4c1c-ac22-ece4b91b1577
In order to get the server running to test this locally, I had to checkout an older commit on the server repo and fiddle with a couple things like the melee range having increased and the IDs being `Int!` type now. We should be prepared to iron out any bugs caused by inconsistencies between the server and client once we get the server's snarky issue resolved.
=> Add action log to display actions resolved in previous phase

client/src/lib/components/sandbox/arena/ArenaCanvasMeleePhase.svelte, client/src/lib/components/sandbox/arena/ArenaCanvasShootingPhase.svelte
- The drawn attack arrows are currently drawn from _under_ the center of the attacking piece to the very edge of the target piece. If the attacking and target pieces are very close to each other, this can result in the attack arrow being very hard to see or straight up not visible if the pieces are touching/overlapping.
- There's a bug which allows you to draft a ranged attack order from a unit which has no ranged attack, like a Swordsman
- There's a bug which allows you to draft a ranged attack targeting a friendly unit
- Draw attack arrows from the center of the attacking piece to slightly before the center of the target piece, _with the arrow drawn on top of the pieces_. This ensures that even if the pieces are very close, you can see the arrow.
- Fix the bugs allowing drafting of …
=> Adjust appearance of attack arrows

client/src/app.css, client/src/lib/components/Header.svelte, client/src/lib/components/modals/DraftUnitModal.svelte, client/src/lib/components/modals/UserModal.svelte, client/src/lib/components/sandbox/squad-selection/MainDraftPage.svelte, client/src/lib/components/utils/NavItem.svelte, client/src/routes/+layout.svelte, client/src/routes/+page.svelte, client/src/routes/enter/+page.svelte
Adding a location where users can manage their keys.  My plan for now is they can toggle between dummy user 1 or their own private key for player 1, and dummy player 2 will continue to be used as the "other" player.
@louiswheeleriv FYI
=> UI changes, adding user modal

src/lib/components/sandbox/arena/HoveredGamePieceTooltipMelee.svelte, src/lib/components/sandbox/arena/HoveredGamePieceTooltipMovement.svelte, src/lib/components/sandbox/arena/HoveredGamePieceTooltipShooting.svelte, src/lib/components/sandbox/arena/HoveredGamePieceTooltipUnitCard.svelte, src/lib/components/sandbox/play/utils.ts
Update the GamePiece hovered tooltip to show:
- The hovered unit's image
- Right now just stubbing them all with the same image, but making it easy to map units to images
- The hovered unit's stats card
- Info on whether this is a valid proposed attack or not
- If a valid proposed attack, show the attacker's stats as well, and the estimated damage
=> Refactor tooltip appearance

src/lib/components/sandbox/play/utils.ts, src/types.d.ts
Looking at all the pieces on the board, it's hard to tell which piece is which unit without having to mouse over each one to see the tooltip. It'd be better if we had icons to differentiate them at a glance.
In the long term we will be better off generating purpose-built icons for the game. FontAwesome icons have been working great for other UI indicators (accuracy, health, etc) but for icons representing specific units, FontAwesome comes up a bit short. Example, they don't have anything good for a spearman or ballista, etc.
FontAwesome will work for this purpose for now though, and it's better than nothing!
=> Draw unit icons on pieces

src/lib/components/sandbox/arena/ArenaCanvasMeleePhase.svelte, src/lib/components/sandbox/arena/ArenaCanvasMovementPhase.svelte, src/lib/components/sandbox/arena/ArenaCanvasShootingPhase.svelte, src/lib/components/sandbox/play/utils.ts
Svelte is not automatically rerendering the component when the arena background image is loaded because the image is drawn on the canvas rather than declared via HTML in the svelte component itself. This results in you loading the page and seeing the following until you do something which triggers the page to rerender, such as mousing over a unit.
- Implement a way to manually trigger an image to be loaded, and the ability to provide a callback to run after the image is loaded.
- When creating the arena phase components, ensure they load the background image and rerender when it's loaded.
Further, this is only an issue the first time you load/refresh the page. Subsequent phase/turn transitions all look fine because the browser has already cached the image.
=> Fix loading of battlefield background image

package-lock.json, package.json, src/lib/components/sandbox/arena/tooltip/HoveredGamePieceTooltipMelee.svelte, src/lib/components/sandbox/arena/tooltip/HoveredGamePieceTooltipMovement.svelte, src/lib/components/sandbox/arena/tooltip/HoveredGamePieceTooltipShooting.svelte, src/lib/components/sandbox/arena/tooltip/tooltip-helpers.ts
If the mouse is toward the bottom of the canvas, push the tooltip up instead of down so it doesn't hang off the bottom and end up unreadable.
=> Push tooltip up if mouse toward bottom

src/lib/components/sandbox/arena/arena-phases/ArenaCanvasMeleePhase.svelte, src/lib/components/sandbox/arena/arena-phases/ArenaCanvasShootingPhase.svelte
Currently in prod we have this situation:
- Piece A makes 3 attacks against Piece B
- We call the dice roll service to make 3 attack roll sequences, call them Roll1, Roll2, and Roll3 (even though each contains multiple rolls)
- We then submit the attack order to the server, but we pass it [Roll3, Roll3, Roll3] instead of [Roll1, Roll2, Roll3]
This PR fixes that.
=> Fix duplicate roll submission

src/lib/components/sandbox/squad-selection/MyUnits.svelte, src/lib/components/sandbox/squad-selection/SquadSelection.svelte
Prime @45930 
On the squad selection page, if you have no PlayerUnits yet, the My Units tab just shows a blank space. Also the buttons for view mode selection could be modified to match the style from the barracks page.
=> Add CTA when no PlayerUnits exist yet

src/lib/components/sandbox/squad-selection/CompleteDraft.svelte
Prime @45930 
After both players select their squads, we display both squads together and give the user a button to start the game, but we don't show the sum of each squad's points like we do during drafting. This isn't hard to add and would improve the view.
=> Show squad points total before starting game

src/lib/components/sandbox/arena/ArenaActionLog.svelte
Prime @45930 
If you fail your hit roll, the wound roll and save roll should never technically happen, and are not worth showing. Similarly, if you pass your hit roll but then fail your wound roll, the save roll should never technically happen.
The action log is currently showing all rolls regardless of whether a previous roll in the attack sequence failed (which should short circuit the attack sequence).
In the following example where `Judgement` is shooting at `Pointy`, only one of its two hit rolls passes. We should therefore only show the wound roll which followed the one successful hit roll. We should not show the wound roll which followed the failed hit roll.
Hide wound/save rolls which follow a failed previous roll in the attack sequence.
=> Fix action log showing unnecessary rolls

src/lib/components/sandbox/arena/tooltip/HoveredGamePieceTooltipMelee.svelte, src/lib/components/sandbox/arena/tooltip/HoveredGamePieceTooltipMovement.svelte, src/lib/components/sandbox/arena/tooltip/HoveredGamePieceTooltipShooting.svelte, src/lib/components/sandbox/arena/tooltip/HoveredGamePieceTooltipUnitCard.svelte
Prime @45930 
Currently the hovered piece tooltip displays vertically, and doesn't display the proposed attack data correctly.
Display the card more horizontally and fix how the proposed attack is displayed.
=> Adjust tooltip unit cards

src/lib/components/sandbox/arena/ArenaActionLog.svelte
If multiple attackers attack the same target, and the target is destroyed before the last attacker goes, then any attackers which are processed after the target is already dead will just have their attacks' `resolvedAttack` value be `null`.
Our action log code is expecting at least one of these attacks to have a `resolvedAttack`, which will not be the case in this scenario, resulting in an exception and the action log showing nothing.
If a piece's attacks were all skipped (such as due to the target being dead) just display a simple message and don't try to show the rolls.
=> Handle skipped attacks due to target already dead
